sudo: true
language: python
python:
  - "3.5"
install: 
  - sudo apt-get install pandoc
  - pip install tox-travis pypandoc
script: tox -e travis
deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    branch: master
